version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
      - rm -rf node_modules
  build:
    commands:
      - npm install --production 
      - npm run build

artifacts:
  files:
    - '**/*'